databases:
  - name: test
    databaseName: 「test_2frc
    user: rails-deploy-1
    region: singapore

services:
  - type: web
    name: rails-deploy-1
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

